/*
 * This file is generated by jOOQ.
 */
package nl.jnext.workshop.testcontainers.vakantieplanner.jooq;


import java.util.Arrays;
import java.util.List;

import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.FlywaySchemaHistory;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Holiday;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Member;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.holiday</code>.
     */
    public final Holiday HOLIDAY = Holiday.HOLIDAY;

    /**
     * The table <code>public.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HOLIDAY_ID_SEQ,
            Sequences.MEMBER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Holiday.HOLIDAY,
            Member.MEMBER);
    }
}
