/*
 * This file is generated by jOOQ.
 */
package nl.jnext.workshop.testcontainers.vakantieplanner.jooq;


import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.FlywaySchemaHistory;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Holiday;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Member;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.holiday</code>.
     */
    public static final Holiday HOLIDAY = Holiday.HOLIDAY;

    /**
     * The table <code>public.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;
}
